version: '3.9.4'

services:
  db:
    image: postgres:14.2-alpine
    expose:
      - "5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orange_county
    ports:
      - "5432:5432"
    networks:
      oc_lettings_network:

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      oc_lettings_network:
    links:
      - db

volumes:
  postgres_data:

networks:
  oc_lettings_network: