#version: '3.9.4-alpine'
#
#services:
#  db:
#    image: postgres:14.2-alpine
#    expose:
#      - "5432"
#    volumes:
#      - ./data/db:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: orange_county
#    ports:
#      - "5432:5432"
#    container_name: db
#
#  web:
#    build: .
#    restart: always
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#    links:
#      - db:db
#
#volumes:
#  postgres_data: