# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  build_test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.9.12-buster
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            pytest -v --no-migrations
      - run:
          name: Run black and flake8
          command: |
            . venv/bin/activate
            black .
            flake8
  build_push_docker_image:
    docker:
      - image: cimg/python:3.9.12-buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push docker image
          command: |
            docker build -t slaffer75/python-oc-lettings-fr_web:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login --username slaffer75 --password-stdin
            docker push slaffer75/python-oc-lettings-fr_web:$CIRCLE_SHA1
  deploy_dev:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-17 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-17 web


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test_build_deploy:
    jobs:
      - build_test
      - build_push_docker_image:
          requires:
            - build_test
          filters:
            branches:
              only: main
      - deploy_dev:
          requires:
            - build_push_docker_image
          filters:
            branches:
              only: main