# Generated by Django 3.0 on 2022-04-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20220408_0507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
